version: "3.8"
services:
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped # 컨테이너 비정상 종료 시 재시작

  backend:
    image: ghcr.io/jinwoole/worklog:0.1 # 로컬 빌드 대신 ghcr.io에서 이미지를 가져오도록 수정
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # application.properties에서 설정한 환경 변수 전달
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB} # db 서비스 이름을 호스트로 사용
    restart: unless-stopped # 컨테이너 비정상 종료 시 재시작

volumes:
  db_data: